// Generated by scripts/generate_design_tokens.py. Do not edit by hand.
// Source: openusage_bar/resources/design-tokens.v1.json (schema 1).
import SwiftUI

extension Color {
    /// Hex color that adapts to the current light/dark appearance.
    init(light: UInt32, dark: UInt32) {
        self.init(light: Color(hex: light), dark: Color(hex: dark))
    }

    init(hex: UInt32) {
        self.init(
            red: Double((hex >> 16) & 0xFF) / 255.0,
            green: Double((hex >> 8) & 0xFF) / 255.0,
            blue: Double(hex & 0xFF) / 255.0
        )
    }

    init(light: Color, dark: Color) {
        #if canImport(UIKit)
        self.init(uiColor: UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
        })
        #else
        self.init(nsColor: NSColor(name: nil) { appearance in
            appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
                ? NSColor(dark) : NSColor(light)
        })
        #endif
    }
}

public enum DesignTokens {
    public static let bg = Color(light: 0xF4F5F7, dark: 0x0C0E12)
    public static let accent = Color(light: 0x087F52, dark: 0x34D399)
    public static let text = Color(light: 0x111114, dark: 0xEAECEF)
    public static let textDim = Color(light: 0x454A55, dark: 0xA7ADB8)
    public static let textFaint = Color(light: 0x5F6570, dark: 0x8A909B)
    public static let hairline = Color(light: 0xD9DDE2, dark: 0x252A31)
    public static let surface = Color(light: 0xFFFFFF, dark: 0x13161B)
    public static let surfaceAlt = Color(light: 0xECEEF1, dark: 0x1A1D23)
    public static let warn = Color(light: 0xB45309, dark: 0xFBBF24)
    public static let bad = Color(light: 0xC0392B, dark: 0xF87171)

    public static let motionFast = 0.15
    public static let motionBase = 0.20
    public static let motionSlow = 0.30
}
