// Generated by scripts/generate_swift_provider_catalog.py. Do not edit.

import Foundation

public enum GeneratedProviderCatalog {
    public static let upstreamVersion = "0.23.0"
    public static let upstreamRevision = "3059f1b"
    public static let upstreamFamilyIDs: Set<String> = [
        "alibaba_cloud",
        "amp",
        "anthropic",
        "azure_openai",
        "claude_code",
        "codebuff",
        "codex",
        "copilot",
        "crush",
        "cursor",
        "deepseek",
        "droid",
        "gemini_api",
        "gemini_cli",
        "goose",
        "groq",
        "hermes",
        "kilo_code",
        "kimi_cli",
        "kiro_cli",
        "mistral",
        "moonshot",
        "mux",
        "ollama",
        "openai",
        "openclaw",
        "opencode",
        "openrouter",
        "perplexity",
        "pi",
        "qwen_cli",
        "roocode",
        "xai",
        "zai",
        "zed",
    ]
    public static let families: [String: ProviderDisplayDescriptor] = [
        "alibaba_cloud": ProviderDisplayDescriptor(
            providerID: "alibaba_cloud",
            familyID: "alibaba_cloud",
            displayName: "Alibaba Cloud",
            category: .api,
            metricFamilies: [.billing, .operational, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "amp": ProviderDisplayDescriptor(
            providerID: "amp",
            familyID: "amp",
            displayName: "Amp",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "anthropic": ProviderDisplayDescriptor(
            providerID: "anthropic",
            familyID: "anthropic",
            displayName: "Anthropic",
            category: .api,
            metricFamilies: [.operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "azure_openai": ProviderDisplayDescriptor(
            providerID: "azure_openai",
            familyID: "azure_openai",
            displayName: "Azure OpenAI",
            category: .api,
            metricFamilies: [.operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "claude_code": ProviderDisplayDescriptor(
            providerID: "claude_code",
            familyID: "claude_code",
            displayName: "Claude Code",
            category: .subscription,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "codebuff": ProviderDisplayDescriptor(
            providerID: "codebuff",
            familyID: "codebuff",
            displayName: "Codebuff",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "codex": ProviderDisplayDescriptor(
            providerID: "codex",
            familyID: "codex",
            displayName: "Codex",
            category: .subscription,
            metricFamilies: [.subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.local, .none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "codex_local_log", sourceKind: "local_log"), ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .supported(.fiveHour, .weekly),
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .supported,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "codex_local_log", sourceKind: "local_log", operatingSystems: [.macOS], stability: .stable, provenance: .providerLocal),
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "copilot": ProviderDisplayDescriptor(
            providerID: "copilot",
            familyID: "copilot",
            displayName: "GitHub Copilot",
            category: .subscription,
            metricFamilies: [.billing, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "crush": ProviderDisplayDescriptor(
            providerID: "crush",
            familyID: "crush",
            displayName: "Crush",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "cursor": ProviderDisplayDescriptor(
            providerID: "cursor",
            familyID: "cursor",
            displayName: "Cursor",
            category: .subscription,
            metricFamilies: [.billing, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "deepseek": ProviderDisplayDescriptor(
            providerID: "deepseek",
            familyID: "deepseek",
            displayName: "DeepSeek",
            category: .api,
            metricFamilies: [.billing, .operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "droid": ProviderDisplayDescriptor(
            providerID: "droid",
            familyID: "droid",
            displayName: "Droid",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "gemini_api": ProviderDisplayDescriptor(
            providerID: "gemini_api",
            familyID: "gemini_api",
            displayName: "Gemini API",
            category: .api,
            metricFamilies: [.operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "gemini_cli": ProviderDisplayDescriptor(
            providerID: "gemini_cli",
            familyID: "gemini_cli",
            displayName: "Gemini CLI",
            category: .subscription,
            metricFamilies: [.subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "goose": ProviderDisplayDescriptor(
            providerID: "goose",
            familyID: "goose",
            displayName: "Goose",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "groq": ProviderDisplayDescriptor(
            providerID: "groq",
            familyID: "groq",
            displayName: "Groq",
            category: .api,
            metricFamilies: [.operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "hermes": ProviderDisplayDescriptor(
            providerID: "hermes",
            familyID: "hermes",
            displayName: "Hermes",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "kilo_code": ProviderDisplayDescriptor(
            providerID: "kilo_code",
            familyID: "kilo_code",
            displayName: "Kilo Code",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "kimi_cli": ProviderDisplayDescriptor(
            providerID: "kimi_cli",
            familyID: "kimi_cli",
            displayName: "Kimi CLI",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "kiro_cli": ProviderDisplayDescriptor(
            providerID: "kiro_cli",
            familyID: "kiro_cli",
            displayName: "Kiro",
            category: .subscription,
            metricFamilies: [.subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.keychain, .none, .oauth],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "kiro_codewhisperer_api", sourceKind: "official_api"), ProviderIdentitySource(credentialSource: "kiro_keychain", sourceKind: "keychain"), ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .supported(.billingCycle),
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .supported,
                billing: .unknown,
                credits: .supported,
                balance: .supported,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "kiro_keychain", sourceKind: "keychain", operatingSystems: [.macOS], stability: .stable, provenance: .providerLocal),
                ProviderSourceCapability(sourceID: "kiro_codewhisperer_api", sourceKind: "official_api", operatingSystems: [.macOS], stability: .stable, provenance: .providerOfficial),
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "minimax": ProviderDisplayDescriptor(
            providerID: "minimax",
            familyID: "minimax",
            displayName: "MiniMax",
            category: .subscription,
            metricFamilies: [.subscriptionQuota],
            credentialSourceTypes: [.apiKey, .none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "minimax_builtin_api", sourceKind: "builtin_api"), ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .supported(.fiveHour, .weekly),
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .supported,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "minimax_builtin_api", sourceKind: "builtin_api", operatingSystems: [.macOS], stability: .stable, provenance: .openUsageBarBuiltIn),
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "mistral": ProviderDisplayDescriptor(
            providerID: "mistral",
            familyID: "mistral",
            displayName: "Mistral",
            category: .api,
            metricFamilies: [.billing, .operational, .subscriptionQuota],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "moonshot": ProviderDisplayDescriptor(
            providerID: "moonshot",
            familyID: "moonshot",
            displayName: "Moonshot",
            category: .api,
            metricFamilies: [.billing, .operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "mux": ProviderDisplayDescriptor(
            providerID: "mux",
            familyID: "mux",
            displayName: "Mux",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "ollama": ProviderDisplayDescriptor(
            providerID: "ollama",
            familyID: "ollama",
            displayName: "Ollama",
            category: .localTool,
            metricFamilies: [.tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .unknown,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "openai": ProviderDisplayDescriptor(
            providerID: "openai",
            familyID: "openai",
            displayName: "OpenAI",
            category: .api,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.apiKey, .none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openai_admin_api", sourceKind: "official_api"), ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .supported,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openai_admin_api", sourceKind: "official_api", operatingSystems: [.macOS], stability: .stable, provenance: .providerOfficial),
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "openclaw": ProviderDisplayDescriptor(
            providerID: "openclaw",
            familyID: "openclaw",
            displayName: "OpenClaw",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "opencode": ProviderDisplayDescriptor(
            providerID: "opencode",
            familyID: "opencode",
            displayName: "OpenCode",
            category: .subscription,
            metricFamilies: [.billing, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "openrouter": ProviderDisplayDescriptor(
            providerID: "openrouter",
            familyID: "openrouter",
            displayName: "OpenRouter",
            category: .api,
            metricFamilies: [.billing, .operational, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "perplexity": ProviderDisplayDescriptor(
            providerID: "perplexity",
            familyID: "perplexity",
            displayName: "Perplexity",
            category: .api,
            metricFamilies: [.billing, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "pi": ProviderDisplayDescriptor(
            providerID: "pi",
            familyID: "pi",
            displayName: "Pi",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "qwen_cli": ProviderDisplayDescriptor(
            providerID: "qwen_cli",
            familyID: "qwen_cli",
            displayName: "Qwen CLI",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "roocode": ProviderDisplayDescriptor(
            providerID: "roocode",
            familyID: "roocode",
            displayName: "Roo Code",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "step_plan": ProviderDisplayDescriptor(
            providerID: "step_plan",
            familyID: "step_plan",
            displayName: "StepFun Step Plan",
            category: .subscription,
            metricFamilies: [.billing, .subscriptionQuota],
            credentialSourceTypes: [.apiKey, .browserSession],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "step_plan_browser_session", sourceKind: "browser_session"), ProviderIdentitySource(credentialSource: "step_plan_official_api", sourceKind: "official_api")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .supported(.fiveHour, .weekly),
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .supported,
                billing: .supported,
                credits: .supported,
                balance: .supported,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "step_plan_browser_session", sourceKind: "browser_session", operatingSystems: [.macOS], stability: .experimental, provenance: .userSession),
                ProviderSourceCapability(sourceID: "step_plan_official_api", sourceKind: "official_api", operatingSystems: [.macOS], stability: .stable, provenance: .providerOfficial),
            ]
        ),
        "xai": ProviderDisplayDescriptor(
            providerID: "xai",
            familyID: "xai",
            displayName: "xAI",
            category: .api,
            metricFamilies: [.billing, .operational],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .unknown,
                modelBreakdown: .unknown,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "zai": ProviderDisplayDescriptor(
            providerID: "zai",
            familyID: "zai",
            displayName: "Z.AI",
            category: .api,
            metricFamilies: [.billing, .operational, .subscriptionQuota, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
        "zed": ProviderDisplayDescriptor(
            providerID: "zed",
            familyID: "zed",
            displayName: "Zed",
            category: .localTool,
            metricFamilies: [.billing, .tokenActivity],
            credentialSourceTypes: [.none],
            acceptedIdentitySources: [ProviderIdentitySource(credentialSource: "openusage", sourceKind: "openusage")],
            capabilityProfile: ProviderCapabilityProfile(
                quotaWindows: .unknown,
                tokenHistory: .supported,
                modelBreakdown: .supported,
                resetTimestamps: .unknown,
                billing: .supported,
                credits: .unknown,
                balance: .unknown,
                cost: .unknown,
                rateLimits: .unknown,
                serviceStatus: .unknown
            ),
            sourceCapabilities: [
                ProviderSourceCapability(sourceID: "openusage", sourceKind: "openusage", operatingSystems: [.macOS], stability: .pinned, provenance: .openUsageUpstream),
            ]
        ),
    ]
}
