// Generate src/styles/tokens.css from the single-source design tokens JSON.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const source = resolve(
  root,
  "openusage_bar/resources/design-tokens.v1.json",
);
const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/styles/tokens.css");

const tokens = JSON.parse(readFileSync(source, "utf8"));
const colors = tokens.color;
const cssKey = (key) => key.replace(/(?<!^)(?=[A-Z])/g, "-").toLowerCase();

const block = (mode) =>
  Object.entries(colors)
    .map(([key, entry]) => `  --${cssKey(key)}: ${entry[mode]};`)
    .join("\n");

const fontSans = tokens.font.sans.join(", ");
const fontMono = tokens.font.mono.join(", ");

const extra = `
  --surface-hover: ${colors.surfaceAlt.light};
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.04);
  --shadow-md: 0 4px 12px rgba(0,0,0,0.06);
  --shadow-lg: 0 10px 30px rgba(0,0,0,0.10);
  --radius-sm: 8px;
  --radius-lg: 14px;
  --radius-xl: 18px;`;

const extraDark = `
    --surface-hover: ${colors.surfaceAlt.dark};
    --shadow-sm: 0 1px 2px rgba(0,0,0,0.18);
    --shadow-md: 0 4px 12px rgba(0,0,0,0.24);
    --shadow-lg: 0 10px 30px rgba(0,0,0,0.34);
    --radius-sm: 8px;
    --radius-lg: 14px;
    --radius-xl: 18px;`;

const css = `/* Generated by web/scripts/gen-tokens.mjs from design-tokens.v1.json. */
:root {
${block("light")}
${extra}
  --radius: ${tokens.radius}px;
  --font-sans: ${fontSans};
  --font-mono: ${fontMono};
  --motion-fast: ${tokens.motion.fast}ms;
  --motion-base: ${tokens.motion.base}ms;
  --motion-slow: ${tokens.motion.slow}ms;
  --ease: ${tokens.motion.ease};
}

@media (prefers-color-scheme: dark) {
  :root {
${block("dark")}
${extraDark}
  }
}
`;

writeFileSync(out, css);
console.log("wrote", out);
