// Generate src/styles/tokens.css from the single-source design tokens JSON.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const source = resolve(
  root,
  "openusage_bar/resources/design-tokens.v1.json",
);
const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/styles/tokens.css");

const tokens = JSON.parse(readFileSync(source, "utf8"));
const colors = tokens.color;
const cssKey = (key) => key.replace(/(?<!^)(?=[A-Z])/g, "-").toLowerCase();

const block = (mode) =>
  Object.entries(colors)
    .map(([key, entry]) => `  --${cssKey(key)}: ${entry[mode]};`)
    .join("\n");

const fontSans = tokens.font.sans.join(", ");
const fontMono = tokens.font.mono.join(", ");

const css = `/* Generated by web/scripts/gen-tokens.mjs from design-tokens.v1.json. */
:root {
${block("light")}
  --radius: ${tokens.radius}px;
  --font-sans: ${fontSans};
  --font-mono: ${fontMono};
  --motion-fast: ${tokens.motion.fast}ms;
  --motion-base: ${tokens.motion.base}ms;
  --motion-slow: ${tokens.motion.slow}ms;
  --ease: ${tokens.motion.ease};
}

@media (prefers-color-scheme: dark) {
  :root {
${block("dark")}
  }
}
`;

writeFileSync(out, css);
console.log("wrote", out);
