#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from openusage_bar.activity_schema import (  # noqa: E402
    EXPECTED_AUTOINCREMENT,
    EXPECTED_INDEXES,
    EXPECTED_SCHEMA,
    LEGACY_SOURCE_SCHEMAS,
)


DEFAULT_OUTPUT = ROOT / "swift_app/Sources/UsageCore/GeneratedActivitySchema.swift"


def swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def column(value: tuple[str, str, int, str | None, int]) -> str:
    name, kind, required, default, primary_key = value
    arguments = [swift_string(name), swift_string(kind)]
    if default is not None:
        arguments.append(f"defaultValue: {swift_string(default)}")
    if primary_key:
        arguments.append(f"primaryKey: {primary_key}")
    method = "required" if required else "optional"
    return f".{method}({', '.join(arguments)})"


def table_contract(version: int) -> dict[str, tuple[tuple[str, str, int, str | None, int], ...]]:
    names = {
        "daily_model_usage", "daily_coverage", "quota_state", "quota_snapshots",
        "source_status", "change_log", "ledger_meta",
    }
    if version >= 2:
        names |= {"daily_costs", "daily_cost_coverage"}
    result = {name: EXPECTED_SCHEMA[name] for name in sorted(names)}
    if version < 3:
        result["daily_model_usage"] = LEGACY_SOURCE_SCHEMAS["daily_model_usage"]
        result["daily_coverage"] = LEGACY_SOURCE_SCHEMAS["daily_coverage"]
    if version < 4:
        result["source_status"] = LEGACY_SOURCE_SCHEMAS["source_status"]
    return result


def render() -> str:
    lines = [
        "// Generated by scripts/generate_swift_activity_schema.py. Do not edit.",
        "",
        "enum GeneratedActivitySchema {",
        "    static func expectedTables(version: Int64) -> [String: [SchemaColumn]] {",
        "        switch version {",
    ]
    for version in range(1, 5):
        lines.extend([f"        case {version}:", "            return ["])
        for table, columns in table_contract(version).items():
            lines.append(f"                {swift_string(table)}: [")
            lines.extend(f"                    {column(item)}," for item in columns)
            lines.append("                ],")
        lines.extend(["            ]"])
    lines.extend([
        "        default:",
        "            return [:]",
        "        }",
        "    }",
        "",
        "    static func expectedIndexes(includeCosts: Bool) -> [ExpectedIndex] {",
        "        var values: [ExpectedIndex] = [",
    ])
    for name, (table, unique, terms) in sorted(EXPECTED_INDEXES.items()):
        if name == "daily_cost_provider_account_day":
            continue
        rendered_terms = ", ".join(
            f"IndexTerm(name: {swift_string(term)}, descending: {'true' if descending else 'false'})"
            for term, descending in terms
        )
        lines.append(
            "            ExpectedIndex("
            f"name: {swift_string(name)}, table: {swift_string(table)}, "
            f"unique: {'true' if unique else 'false'}, partial: false, "
            f"terms: [{rendered_terms}]),"
        )
    cost_table, cost_unique, cost_terms = EXPECTED_INDEXES["daily_cost_provider_account_day"]
    rendered_cost_terms = ", ".join(
        f"IndexTerm(name: {swift_string(term)}, descending: {'true' if descending else 'false'})"
        for term, descending in cost_terms
    )
    lines.extend([
        "        ]",
        "        if includeCosts {",
        "            values.append(ExpectedIndex("
        f"                name: {swift_string('daily_cost_provider_account_day')}, table: {swift_string(cost_table)},",
        f"                unique: {'true' if cost_unique else 'false'}, partial: false, terms: [{rendered_cost_terms}]",
        "            ))",
        "        }",
        "        return values",
        "    }",
        "",
        "    static let autoincrementColumns: [String: String] = [",
    ])
    lines.extend(
        f"        {swift_string(table)}: {swift_string(column_name)},"
        for table, column_name in sorted(EXPECTED_AUTOINCREMENT.items())
    )
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
