#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from openusage_bar.provider_catalog import (  # noqa: E402
    QuotaWindowCapability,
    load_provider_catalog,
)


MANIFEST = ROOT / "openusage_bar/resources/provider-catalog.v1.json"
DEFAULT_OUTPUT = ROOT / "swift_app/Sources/UsageCore/GeneratedProviderCatalog.swift"
CATEGORY_CASES = {
    "api": "api",
    "local_tool": "localTool",
    "subscription": "subscription",
}
METRIC_CASES = {
    "billing": "billing",
    "operational": "operational",
    "subscription_quota": "subscriptionQuota",
    "token_activity": "tokenActivity",
}
CREDENTIAL_CASES = {
    "provider_owned": "none",
    "api_key": "apiKey",
    "oauth": "oauth",
    "cli": "cli",
    "local": "local",
    "keychain": "keychain",
    "browser_session": "browserSession",
}
CAPABILITY_STATE_CASES = {
    "supported": "supported",
    "unsupported": "unsupported",
    "unknown": "unknown",
}
QUOTA_WINDOW_CASES = {
    "session": "session",
    "five_hour": "fiveHour",
    "weekly": "weekly",
    "monthly": "monthly",
    "billing_cycle": "billingCycle",
    "model_specific": "modelSpecific",
}
OPERATING_SYSTEM_CASES = {
    "macos": "macOS",
    "windows": "windows",
    "linux": "linux",
}
STABILITY_CASES = {
    "stable": "stable",
    "experimental": "experimental",
    "pinned": "pinned",
    "opaque": "opaque",
}
PROVENANCE_CASES = {
    "openusage_upstream": "openUsageUpstream",
    "openusage_bar_builtin": "openUsageBarBuiltIn",
    "provider_official": "providerOfficial",
    "provider_local": "providerLocal",
    "user_session": "userSession",
}


def swift_string(value: str) -> str:
    common = {
        "\0": "\\0",
        "\t": "\\t",
        "\n": "\\n",
        "\r": "\\r",
        '"': '\\"',
        "\\": "\\\\",
    }
    escaped: list[str] = []
    for scalar in value:
        if scalar in common:
            escaped.append(common[scalar])
        elif unicodedata.category(scalar) == "Cc":
            escaped.append(f"\\u{{{ord(scalar):x}}}")
        else:
            escaped.append(scalar)
    return '"' + "".join(escaped) + '"'


def swift_cases(values: list[str]) -> str:
    return "[" + ", ".join(f".{value}" for value in values) + "]"


def swift_quota_capability(capability: QuotaWindowCapability) -> str:
    state = CAPABILITY_STATE_CASES[capability.state]
    if capability.state != "supported":
        return f".{state}"
    values = ", ".join(
        f".{QUOTA_WINDOW_CASES[value]}" for value in capability.values
    )
    return f".supported({values})"


def render() -> str:
    catalog = load_provider_catalog(MANIFEST)
    lines = [
        "// Generated by scripts/generate_swift_provider_catalog.py. Do not edit.",
        "",
        "import Foundation",
        "",
        "public enum GeneratedProviderCatalog {",
        f"    public static let upstreamVersion = {swift_string(catalog.upstream_version)}",
        f"    public static let upstreamRevision = {swift_string(catalog.upstream_revision)}",
        "    public static let upstreamFamilyIDs: Set<String> = [",
        *(
            f"        {swift_string(family_id)},"
            for family_id in sorted(catalog.upstream_family_ids)
        ),
        "    ]",
        "    public static let families: [String: ProviderDisplayDescriptor] = [",
    ]
    for family in catalog.families:
        category = CATEGORY_CASES[family.category]
        metrics = [METRIC_CASES[value] for value in sorted(family.metric_families)]
        credentials = sorted(
            {CREDENTIAL_CASES[source.credential_type] for source in family.sources}
        )
        identity_sources = sorted(
            (source.source_id, source.kind) for source in family.sources
        )
        swift_identity_sources = "[" + ", ".join(
            "ProviderIdentitySource(credentialSource: "
            f"{swift_string(source_id)}, sourceKind: {swift_string(kind)})"
            for source_id, kind in identity_sources
        ) + "]"
        capabilities = family.capabilities
        quota_windows = swift_quota_capability(capabilities.quota_windows)
        swift_regions = "[" + ", ".join(swift_string(value) for value in sorted(family.regions)) + "]"
        swift_sources = [
            "                ProviderSourceCapability("
            f"sourceID: {swift_string(source.source_id)}, "
            f"sourceKind: {swift_string(source.kind)}, "
            f"operatingSystems: {swift_cases([OPERATING_SYSTEM_CASES[value] for value in sorted(source.operating_systems)])}, "
            f"stability: .{STABILITY_CASES[source.stability]}, "
            f"provenance: .{PROVENANCE_CASES[source.provenance]}),"
            for source in family.sources
        ]
        lines.extend(
            [
                f"        {swift_string(family.family_id)}: ProviderDisplayDescriptor(",
                f"            providerID: {swift_string(family.family_id)},",
                f"            familyID: {swift_string(family.family_id)},",
                f"            displayName: {swift_string(family.display_name)},",
                f"            category: .{category},",
                f"            metricFamilies: {swift_cases(metrics)},",
                f"            regions: {swift_regions},",
                f"            supportsAccounts: {str(family.supports_accounts).lower()},",
                f"            credentialSourceTypes: {swift_cases(credentials)},",
                f"            acceptedIdentitySources: {swift_identity_sources},",
                "            capabilityProfile: ProviderCapabilityProfile(",
                f"                quotaWindows: {quota_windows},",
                f"                tokenHistory: .{CAPABILITY_STATE_CASES[capabilities.token_history]},",
                f"                modelBreakdown: .{CAPABILITY_STATE_CASES[capabilities.model_breakdown]},",
                f"                resetTimestamps: .{CAPABILITY_STATE_CASES[capabilities.reset_timestamps]},",
                f"                billing: .{CAPABILITY_STATE_CASES[capabilities.billing]},",
                f"                credits: .{CAPABILITY_STATE_CASES[capabilities.credits]},",
                f"                balance: .{CAPABILITY_STATE_CASES[capabilities.balance]},",
                f"                cost: .{CAPABILITY_STATE_CASES[capabilities.cost]},",
                f"                rateLimits: .{CAPABILITY_STATE_CASES[capabilities.rate_limits]},",
                f"                serviceStatus: .{CAPABILITY_STATE_CASES[capabilities.service_status]}",
                "            ),",
                "            sourceCapabilities: [",
                *swift_sources,
                "            ]",
                "        ),",
            ]
        )
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Swift provider catalog")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    output = arguments.output.resolve()
    if arguments.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != generated:
            print(f"generated Swift provider catalog is stale: {output}", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
