#!/usr/bin/env python3
"""Generate SwiftUI design tokens from the single-source design-tokens JSON.

The JSON at ``openusage_bar/resources/design-tokens.v1.json`` is the source of
truth shared by the Web dashboard (Python reads it directly) and the native
SwiftUI clients (this generator emits a Swift file that must stay in sync).
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def _hex_to_rgb(value: str) -> tuple[int, int, int]:
    match = re.fullmatch(r"#([0-9a-fA-F]{6})", value)
    if match is None:
        raise ValueError(f"invalid hex color: {value!r}")
    raw = match.group(1)
    return tuple(int(raw[index : index + 2], 16) for index in (0, 2, 4))  # type: ignore[return-value]


def _swift_color(light: str, dark: str) -> str:
    lr, lg, lb = _hex_to_rgb(light)
    dr, dg, db = _hex_to_rgb(dark)
    return (
        "Color(light: 0x%02X%02X%02X, dark: 0x%02X%02X%02X)"
        % (lr, lg, lb, dr, dg, db)
    )


def generate(payload: dict, name: str) -> str:
    colors = payload["color"]
    motion = payload["motion"]
    lines = [
        "// Generated by scripts/generate_design_tokens.py. Do not edit by hand.",
        f"// Source: openusage_bar/resources/design-tokens.v1.json (schema {payload['schemaVersion']}).",
        "import SwiftUI",
        "",
        "extension Color {",
        "    /// Hex color that adapts to the current light/dark appearance.",
        "    init(light: UInt32, dark: UInt32) {",
        "        self.init(light: Color(hex: light), dark: Color(hex: dark))",
        "    }",
        "",
        "    init(hex: UInt32) {",
        "        self.init(",
        "            red: Double((hex >> 16) & 0xFF) / 255.0,",
        "            green: Double((hex >> 8) & 0xFF) / 255.0,",
        "            blue: Double(hex & 0xFF) / 255.0",
        "        )",
        "    }",
        "",
        "    init(light: Color, dark: Color) {",
        "        #if canImport(UIKit)",
        "        self.init(uiColor: UIColor { traits in",
        "            traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)",
        "        })",
        "        #else",
        "        self.init(nsColor: NSColor(name: nil) { appearance in",
        "            appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua",
        "                ? NSColor(dark) : NSColor(light)",
        "        })",
        "        #endif",
        "    }",
        "}",
        "",
        f"public enum {name} {{",
    ]
    semantic = [
        "bg",
        "accent",
        "text",
        "textDim",
        "textFaint",
        "hairline",
        "surface",
        "surfaceAlt",
        "warn",
        "bad",
    ]
    for key in semantic:
        entry = colors[key]
        lines.append(f"    public static let {key} = {_swift_color(entry['light'], entry['dark'])}")
    lines.extend(
        [
            "",
            "    public static let motionFast = 0.15",
            "    public static let motionBase = 0.20",
            "    public static let motionSlow = 0.30",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main(arguments: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parsed = parser.parse_args(arguments)
    payload = json.loads(parsed.source.read_text(encoding="utf-8"))
    generated = generate(payload, "DesignTokens")
    parsed.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
